### ISSUE TITLE
RMK Sem 4 PROBABILITY AND QUEUING THEORY  Unit 5 CS

### ISSUE THREAD

**Issue by meenakshy7** [edwisely-ai/Content#114]

**Comment by RAJASEKHAR36** [comment]
@meenakshy7 
The cs sheet and decks are moved to the staging.
Please go on with the QC.

**Comment by meenakshy7** [comment]
@RAJASEKHAR36 The QC is completed. Decks can be moved to production.

**Comment by RAJASEKHAR36** [comment]
@meenakshy7 
The cs sheet is moved to the production.
Please check it once.
