### ISSUE TITLE
RMK Sem 4 PROBABILITY AND RANDOM PROCESSES  Unit 5 CS

### ISSUE THREAD

**Issue by meenakshy7** [edwisely-ai/Content#117]

**Comment by meenakshy7** [comment]
@RAJASEKHAR36 Please upload the CS sheet and Deck mapping to staging (ECE Unit 5).

CS sheet: [https://app.zenhub.com/files/350607556/1fe6ec3f-af90-4a32-a1e5-29a82c9be01c/download](https://app.zenhub.com/files/350607556/1fe6ec3f-af90-4a32-a1e5-29a82c9be01c/download)
Deck mapping: [https://app.zenhub.com/files/350607556/bcb5caec-bd3a-4915-8782-28c42cc62646/download](https://app.zenhub.com/files/350607556/bcb5caec-bd3a-4915-8782-28c42cc62646/download)

**Comment by RAJASEKHAR36** [comment]
@meenakshy7 
The above cs sheet is moved to the staging.
Please go on with the QC.

**Comment by meenakshy7** [comment]
@RAJASEKHAR36 The QC is completed. Decks can be moved to production.

**Comment by RAJASEKHAR36** [comment]
@meenakshy7 
The above cs sheet is moved to the Production.
Please check it once.
