### ISSUE TITLE
RMK Sem 4 PROBABILITY AND STATISTICS Unit 5 CS

### ISSUE THREAD

**Issue by meenakshy7** [edwisely-ai/Content#120]

**Comment by meenakshy7** [comment]
@RAJASEKHAR36 Please upload the CS sheet and Deck mapping to staging. (IT Unit 5)

CS sheet: [https://app.zenhub.com/files/350607556/f9286636-a56f-42b9-b4d5-5f3713523514/download](https://app.zenhub.com/files/350607556/f9286636-a56f-42b9-b4d5-5f3713523514/download)
Deck mapping: [https://app.zenhub.com/files/350607556/da34d3a7-2d97-4643-b08e-b1ae7e5714b2/download](https://app.zenhub.com/files/350607556/da34d3a7-2d97-4643-b08e-b1ae7e5714b2/download)

**Comment by RAJASEKHAR36** [comment]
@meenakshy7 
The decks are moved to the staging.
Please go on with the QC with the credentials RMKIT04.

**Comment by meenakshy7** [comment]
@RAJASEKHAR36 QC is completed. Please move the decks to production.

**Comment by RAJASEKHAR36** [comment]
@meenakshy7
The decks are moved to the Production
Please check it once.
