### ISSUE TITLE
Physics for Civil Engineering Unit 3 AQ

### ISSUE THREAD

**Issue by meenakshy7** [edwisely-ai/Content#160]

**Comment by Eshu-99** [comment]
Hello @kumarAman-123 

         PFA, Typing completed

[https://app.zenhub.com/files/350607556/a2374727-b85f-48be-a4d8-a7bb08a1066e/download](https://app.zenhub.com/files/350607556/a2374727-b85f-48be-a4d8-a7bb08a1066e/download)

**Comment by kumarAman-123** [comment]
@RAJASEKHAR36 
Hello sir ! Pls upload these questions.
[https://app.zenhub.com/files/350607556/fb9e6f57-de15-4c34-aa31-ffdcc0d2a1af/download](https://app.zenhub.com/files/350607556/fb9e6f57-de15-4c34-aa31-ffdcc0d2a1af/download)

**Comment by RAJASEKHAR36** [comment]
Hi Aman
The above attached questions are uploaded.
