### ISSUE TITLE
Construction Techniques-Unit 5-CS

### ISSUE THREAD

**Issue by Spandana-23** [edwisely-ai/Content#173]

**Comment by Kiranedwisely** [comment]
@RAJASEKHAR36 
CS sheet for CT-unit-5 is ready. Please upload them for staging

[https://app.zenhub.com/files/350607556/ac952c96-0124-4cec-9b91-52b7ecde3447/download](https://app.zenhub.com/files/350607556/ac952c96-0124-4cec-9b91-52b7ecde3447/download)

**Comment by RAJASEKHAR36** [comment]
@Kiranedwisely 
The CS sheet is moved to the staging.
Please go on with the QC with the credentials of RMKCE04.

**Comment by Kiranedwisely** [comment]
@RAJASEKHAR36 
QC for above mentioned topic is done & can be moved for production

**Comment by RAJASEKHAR36** [comment]
@Kiranedwisely
The above cs sheet is moved to the production.
Please check it once
