### ISSUE TITLE
Applied Hydraulics- Unit 5-CS

### ISSUE THREAD

**Issue by Spandana-23** [edwisely-ai/Content#174]

**Comment by Spandana-23** [comment]
@RAJASEKHAR36 
Please upload the CS sheet of U-5 AH to staging.
PFA.
[https://app.zenhub.com/files/350607556/c163e1a3-1fe4-4836-b9c3-a4f76a1b338b/download](https://app.zenhub.com/files/350607556/c163e1a3-1fe4-4836-b9c3-a4f76a1b338b/download)

**Comment by RAJASEKHAR36** [comment]
@Spandana-23 
The cs sheet is moved to the staging.
Please go on with the QC.

**Comment by Spandana-23** [comment]
@RAJASEKHAR36 
QC is done, they can be moved to production.

**Comment by RAJASEKHAR36** [comment]
@Spandana-23
The above cs sheet is moved to the production.
Please check it once.
