### ISSUE TITLE
Manufacturing tech 2- unit 5- CS

### ISSUE THREAD

**Issue by karneprudhvi** [edwisely-ai/Content#177]

**Comment by karneprudhvi** [comment]
@RAJASEKHAR36 PFA and upload the file to staging for QC 

[https://app.zenhub.com/files/350607556/774a6d90-da41-4cc9-8483-b37f835534d5/download](https://app.zenhub.com/files/350607556/774a6d90-da41-4cc9-8483-b37f835534d5/download)

**Comment by RAJASEKHAR36** [comment]
@karneprudhvi 
The cs sheet is moved to the staging
Please go on with the QC.

**Comment by karneprudhvi** [comment]
@RAJASEKHAR36 @Madandamara  done with QC move to production

**Comment by RAJASEKHAR36** [comment]
@karneprudhvi 
The cs sheet is moved to the Prod
Please check it once.
