### ISSUE TITLE
Thermal engineering 1- unit 4- CS

### ISSUE THREAD

**Issue by karneprudhvi** [edwisely-ai/Content#182]

**Comment by Eshu-99** [comment]
Hi Prudhvi,  
   PFA, HTML Files completed

[https://app.zenhub.com/files/350607556/3726f737-0d9c-45aa-9bdf-9582a8839998/download](https://app.zenhub.com/files/350607556/3726f737-0d9c-45aa-9bdf-9582a8839998/download)

**Comment by karneprudhvi** [comment]
@RAJASEKHAR36 PFA and upload the summary sheet to stagging for QC

[https://app.zenhub.com/files/350607556/5fb82949-5ebe-42a6-8298-15d722cad2fa/download](https://app.zenhub.com/files/350607556/5fb82949-5ebe-42a6-8298-15d722cad2fa/download)

**Comment by RAJASEKHAR36** [comment]
@karneprudhvi 
The sheet is moved to the staging 
please go on with the QC with the credentials RMKME04.

**Comment by karneprudhvi** [comment]
@RAJASEKHAR36 @Madandamara Done with QC move to production
