### ISSUE TITLE
Building Materials-Unit 4- CS

### ISSUE THREAD

**Issue by Spandana-23** [edwisely-ai/Content#186]

**Comment by Spandana-23** [comment]
@RAJASEKHAR36 
Please upload the CS sheet and deck mapping for U-4 to staging. PFA.
[https://app.zenhub.com/files/350607556/5cfe32c1-afde-4571-aaa9-be6e1a8312a2/download](https://app.zenhub.com/files/350607556/5cfe32c1-afde-4571-aaa9-be6e1a8312a2/download)
[https://app.zenhub.com/files/350607556/e99ae7cc-6ade-4309-b940-c6e28df43814/download](https://app.zenhub.com/files/350607556/e99ae7cc-6ade-4309-b940-c6e28df43814/download)

**Comment by RAJASEKHAR36** [comment]
@Spandana-23 
The above attached cs sheet and decks are uploaded to the staging.
Please go on with the QC with the credentials RMKEC1.

**Comment by Spandana-23** [comment]
@RAJASEKHAR36 
QC is done,they can be moved to production.

**Comment by RAJASEKHAR36** [comment]
@Spandana-23 
It is moved to the production.
Please check it once.
