### ISSUE TITLE
SOM Mech-Unit 3-CS

### ISSUE THREAD

**Issue by Spandana-23** [edwisely-ai/Content#189]

**Comment by RAJASEKHAR36** [comment]
@Kiranedwisely 
The above cs sheet is moved to the staging.
Please go on with the QC with the credentials RMKME04.

**Comment by Kiranedwisely** [comment]
@RAJASEKHAR36 
QC for above mentioned topics is done. They can be moved for production

**Comment by RAJASEKHAR36** [comment]
@Kiranedwisely
The above cs sheet is moved to the production.
Please check it once
