### ISSUE TITLE
SOM Mech- Unit 4-CS

### ISSUE THREAD

**Issue by Spandana-23** [edwisely-ai/Content#190]

**Comment by Eshu-99** [comment]
Hi@Spandana-23  @Kiranedwisely ,

PFA, Typing completed

[https://app.zenhub.com/files/350607556/2854e141-8527-4b3e-a9b2-af7a7ae7bdba/download](https://app.zenhub.com/files/350607556/2854e141-8527-4b3e-a9b2-af7a7ae7bdba/download)

**Comment by Spandana-23** [comment]
@RAJASEKHAR36 
Please upload the CS of U-4 Mechanical SOM to staging. Please find the attachement for CS Sheet and Deck mapping.
[https://app.zenhub.com/files/350607556/8a6a9f7f-3e75-4a93-bd54-c67fc6d001d0/download](https://app.zenhub.com/files/350607556/8a6a9f7f-3e75-4a93-bd54-c67fc6d001d0/download)
[https://app.zenhub.com/files/350607556/9691a17e-75ec-48ec-be31-903a8cb61518/download](https://app.zenhub.com/files/350607556/9691a17e-75ec-48ec-be31-903a8cb61518/download)

**Comment by RAJASEKHAR36** [comment]
@Kiranedwisely
The above cs sheet is moved to the staging.
Please go on with the QC with the credentials RMKME04.

**Comment by Kiranedwisely** [comment]
@RAJASEKHAR36 
Above mentioned topic is done with QC, ready for production

**Comment by RAJASEKHAR36** [comment]
@Kiranedwisely
The above cs sheet is moved to the production.
Please check it once
