### ISSUE TITLE
SOM Mech-Unit 5- CS

### ISSUE THREAD

**Issue by Spandana-23** [edwisely-ai/Content#191]

**Comment by Spandana-23** [comment]
@RAJASEKHAR36 
Please upload the CS of U-5 to staging and production. Please find the attachment for deckmapping.
[https://app.zenhub.com/files/350607556/a36d8f59-7a4b-47a4-9315-f5ee0e7f5024/download](https://app.zenhub.com/files/350607556/a36d8f59-7a4b-47a4-9315-f5ee0e7f5024/download)

**Comment by RAJASEKHAR36** [comment]
@Spandana-23 
CS sheet is not attached
Please check it and send

**Comment by Spandana-23** [comment]
@RAJASEKHAR36 
There is no CS sheet prepared for this Unit because we have already existing decks.
