### ISSUE TITLE
CIRCUIT THEORY-UNIT 1-ASSEMENT QUESTIONS (FACULTY)

### ISSUE THREAD

**Issue by suresh-edwisely** [edwisely-ai/Content#196]

**Comment by suresh-edwisely** [comment]
@RAJASEKHAR36 [https://app.zenhub.com/files/350607556/e58c42be-1551-47a5-92ed-1b147b74d844/download](https://app.zenhub.com/files/350607556/e58c42be-1551-47a5-92ed-1b147b74d844/download)

**Comment by RAJASEKHAR36** [comment]
@suresh-edwisely 
The questions are uploaded
