### ISSUE TITLE
Communication Theory - Unit 4 - CS

### ISSUE THREAD

**Issue by GauriKale97** [edwisely-ai/Content#197]

**Comment by GauriKale97** [comment]
[https://app.zenhub.com/files/350607556/cfd0ba87-9bc8-4126-9cb1-3989aee7aae4/download](https://app.zenhub.com/files/350607556/cfd0ba87-9bc8-4126-9cb1-3989aee7aae4/download)

[https://app.zenhub.com/files/350607556/29e4d389-d399-4479-a66d-9d8fa6c77585/download](https://app.zenhub.com/files/350607556/29e4d389-d399-4479-a66d-9d8fa6c77585/download)

**Comment by Eshu-99** [comment]
Hi Gauri,

PFA, Typing completed

[https://app.zenhub.com/files/350607556/013c135b-a0b6-4ef9-b653-bfbe045d4440/download](https://app.zenhub.com/files/350607556/013c135b-a0b6-4ef9-b653-bfbe045d4440/download)

**Comment by RAJASEKHAR36** [comment]
The cs sheet is moved to the production.
