### ISSUE TITLE
EMF - Unit 4 - CS

### ISSUE THREAD

**Issue by GauriKale97** [edwisely-ai/Content#198]

**Comment by GauriKale97** [comment]
[https://app.zenhub.com/files/350607556/4525b700-d651-4fe9-8b93-a306dd0a5902/download](https://app.zenhub.com/files/350607556/4525b700-d651-4fe9-8b93-a306dd0a5902/download)

[https://app.zenhub.com/files/350607556/62f12ac2-aa82-408b-92af-4ec074b0c22b/download](https://app.zenhub.com/files/350607556/62f12ac2-aa82-408b-92af-4ec074b0c22b/download)

**Comment by KALYANMADDALI** [comment]
@GauriKale97 work is done and check once html cards
[unit_4_EMF _ HTML Cards.zip](https://github.com/edwisely-ai/Content/files/6432070/unit_4_EMF._.HTML.Cards.zip)

**Comment by RAJASEKHAR36** [comment]
The cs sheet is moved to the production.
