### ISSUE TITLE
LICA - Unit 5 - CS

### ISSUE THREAD

**Issue by GauriKale97** [edwisely-ai/Content#273]
HTML cards from page no. 129 (5.3 Sine wave) to 180 (Opto coupler IC) 

[https://app.zenhub.com/files/350607556/bbaca6f6-afbd-48fe-9007-5eb8e759fd05/download](https://app.zenhub.com/files/350607556/bbaca6f6-afbd-48fe-9007-5eb8e759fd05/download)

**Comment by GauriKale97** [comment]
Not 129 ...from page no. 132

**Comment by KALYANMADDALI** [comment]
@GauriKale97 this pdf document typing is completed and file shared to you and suresh please find your google drive

**Comment by RAJASEKHAR36** [comment]
The cs sheet is moved to the production.
