### ISSUE TITLE
Physics for Information science  Unit 4 AQ

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#296]

**Comment by kumarAman-123** [comment]
Hello @Eshu-99 !! Please type these questions.

https://docs.google.com/document/d/1_T2BZUXxcQeVQ1AgCTMW-r3jF9EpW7ZCMR7NWjPo8W8/edit#heading=h.h82bjsyt3pvh

**Comment by Eshu-99** [comment]
@kumarAman-123 

PFA, AQ's completed

[https://app.zenhub.com/files/350607556/7bdd3e95-bb9b-4f7b-ab88-101ac578e743/download](https://app.zenhub.com/files/350607556/7bdd3e95-bb9b-4f7b-ab88-101ac578e743/download)

**Comment by kumarAman-123** [comment]
Hello @RAJASEKHAR36 , Pls upload this document.

[https://app.zenhub.com/files/350607556/59e0bc33-0385-4feb-9716-30b42a2c3eca/download](https://app.zenhub.com/files/350607556/59e0bc33-0385-4feb-9716-30b42a2c3eca/download)

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 
The above attached questions are uploaded.
