### ISSUE TITLE
Physics for information science Unit 5 AQ

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#299]

**Comment by kumarAman-123** [comment]
hello @Eshu-99 !! Pls type this document.
https://docs.google.com/document/d/1JBHReGF-t05YNLTIfNrWArp0WV0EA2p47kC7gGh2HzQ/edit#

**Comment by Eshu-99** [comment]
@kumarAman-123 

PFA

[https://app.zenhub.com/files/350607556/aa09fc11-d280-4765-bd62-532717594a25/download](https://app.zenhub.com/files/350607556/aa09fc11-d280-4765-bd62-532717594a25/download)
