### ISSUE TITLE
Physics for electronics engineering Unit 4 AQ

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#300]

**Comment by kumarAman-123** [comment]
hello @Eshu-99  !
Pls type this document.
https://docs.google.com/document/d/1ySH8VJzcdDyUg-NRQIrOIVSYAi68JWNzk7xHKYTiWGU/edit#

**Comment by Eshu-99** [comment]
Hi Aman

PFA, AQ's completed

[https://app.zenhub.com/files/350607556/a1ebf34b-ef81-453a-bb98-43daa254b3ca/download](https://app.zenhub.com/files/350607556/a1ebf34b-ef81-453a-bb98-43daa254b3ca/download)

**Comment by kumarAman-123** [comment]
Hello @RAJASEKHAR36  Pls upload this document.
[https://app.zenhub.com/files/350607556/2bcf9910-7ca6-4d96-908f-e366c05029e8/download](https://app.zenhub.com/files/350607556/2bcf9910-7ca6-4d96-908f-e366c05029e8/download)

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 
The above attached questions are uploaded.

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 
The above attached questions are uploaded.
