### ISSUE TITLE
Physics for electronics engineering Unit 5 AQ

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#302]

**Comment by kumarAman-123** [comment]
hello @Eshu-99 
Please type this document.
https://docs.google.com/document/d/17VqLqKLRxl5nQsHpPTCxhJ9ErVLFoE0RXYbVyw7qW50/edit#

**Comment by Eshu-99** [comment]
@kumarAman-123 

PFA, AQ typing completed

[https://app.zenhub.com/files/350607556/7a93f0c8-35dc-4e2b-a438-3ee897c7f502/download](https://app.zenhub.com/files/350607556/7a93f0c8-35dc-4e2b-a438-3ee897c7f502/download)

**Comment by kumarAman-123** [comment]
Hello @RAJASEKHAR36 , Pls type this document
[https://app.zenhub.com/files/350607556/fa0d224d-db5a-4384-b11d-104d22b6d803/download](https://app.zenhub.com/files/350607556/fa0d224d-db5a-4384-b11d-104d22b6d803/download)

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 
There is no blooms taxonomy and difficulty lever in the above attached sheet.
Please fill the gap and resend it.

**Comment by kumarAman-123** [comment]
Hello @RAJASEKHAR36 . pls upload this document. BL and DL tagging done.
[https://app.zenhub.com/files/350607556/f338c615-3975-426d-be31-1a384c6645d1/download](https://app.zenhub.com/files/350607556/f338c615-3975-426d-be31-1a384c6645d1/download)

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 
The above attached questions are uploaded.
