### ISSUE TITLE
Physics for civil engineering Unit 5 AQ

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#307]

**Comment by kumarAman-123** [comment]
Hello @Eshu-99 , Pls type the following document.
https://docs.google.com/document/d/1TaB78PfeOElqcNu6usCBGNUdkcLi4ZCp2h4AR797RPI/edit#

**Comment by Eshu-99** [comment]
@kumarAman-123 

PFA, AQ's typing completed

[https://app.zenhub.com/files/350607556/9d7de9e1-2c55-4db4-a2c3-6c186bfc0823/download](https://app.zenhub.com/files/350607556/9d7de9e1-2c55-4db4-a2c3-6c186bfc0823/download)

**Comment by kumarAman-123** [comment]
hello @RAJASEKHAR36 
Pls upload this document sir.
[https://app.zenhub.com/files/350607556/25ea38cd-8dea-4389-8f91-bda675dde45f/download](https://app.zenhub.com/files/350607556/25ea38cd-8dea-4389-8f91-bda675dde45f/download)

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123
The above attached questions are uploaded.
