### ISSUE TITLE
Unit 1- CS&BS - AQ

### ISSUE THREAD

**Issue by GauriKale97** [edwisely-ai/Content#309]
Hi Ma'am 
PFA 

https://docs.google.com/document/d/13J_6SSolv7UrPUC68XqOmqxSlk_lAW8veM2DzUbs02E/edit

Please move them to excel sheet

**Comment by Eshu-99** [comment]
@GauriKale97 


PFA, AQs typing completed
[https://app.zenhub.com/files/350607556/71c30948-d8af-4594-9d0f-5349bb39865b/download](https://app.zenhub.com/files/350607556/71c30948-d8af-4594-9d0f-5349bb39865b/download)
