### ISSUE TITLE
Physics for Mechanical engineering Unit 5 AQ

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#316]

**Comment by kumarAman-123** [comment]
Hello @Eshu-99 pls type the following document.
https://docs.google.com/document/d/1KrNdp4Mq1a8Dnusrh6PMxFvt8FVl6PDUzQ0DxfQZDkA/edit#

**Comment by Eshu-99** [comment]
PFA, AQs completed

[https://app.zenhub.com/files/350607556/efb236d8-1f49-4dab-9d24-8360c92e2edf/download](https://app.zenhub.com/files/350607556/efb236d8-1f49-4dab-9d24-8360c92e2edf/download)

**Comment by kumarAman-123** [comment]
Hello @RAJASEKHAR36 , Pls upload the following document.[https://app.zenhub.com/files/350607556/0f8b3ebd-77f4-4512-8eb7-8f57ca343e8d/download](https://app.zenhub.com/files/350607556/0f8b3ebd-77f4-4512-8eb7-8f57ca343e8d/download)

**Comment by kumarAman-123** [comment]
@RAJASEKHAR36 ..pls upload these assesment questions also.

**Comment by meenakshy7** [comment]
@kumarAman-123 The questions are uploaded. Please check them once.
