### ISSUE TITLE
Physics for Information science Unit 4 CS

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#317]

**Comment by kumarAman-123** [comment]
hello @Eshu-99 . Please type the following document.
https://docs.google.com/document/d/1RnfNOG6UdfjvWHGHIRQN1cZwxV_MX1GwOqs-rHkwEng/edit#

**Comment by Eshu-99** [comment]
@kumarAman-123 

PFA,  HTML Files completed

[https://app.zenhub.com/files/350607556/4ac6d1ef-7349-4608-a972-335f52dd48e7/download](https://app.zenhub.com/files/350607556/4ac6d1ef-7349-4608-a972-335f52dd48e7/download)

**Comment by kumarAman-123** [comment]
Hello @RAJASEKHAR36 , please upload the following summary sheet.[https://app.zenhub.com/files/350607556/b4b2b551-6f6d-4b5d-9d9f-4051716365d7/download](https://app.zenhub.com/files/350607556/b4b2b551-6f6d-4b5d-9d9f-4051716365d7/download)

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 
Please go on with the QC with RMKCS1.

**Comment by kumarAman-123** [comment]
@RAJASEKHAR36 @meenakshy7,,QC at the staging is done.

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 @meenakshy7 
It is moved to prod.
Please check it once
