### ISSUE TITLE
Structural analysis-Unit 1-CS

### ISSUE THREAD

**Issue by Spandana-23** [edwisely-ai/Content#328]

**Comment by Kiranedwisely** [comment]
File is shared through Mail
@KALYANMADDALI

**Comment by Eshu-99** [comment]
@Kiranedwisely 

PFA, Typing completed

[https://app.zenhub.com/files/350607556/1c160ca1-0352-44df-9a14-9964aaa343bd/download](https://app.zenhub.com/files/350607556/1c160ca1-0352-44df-9a14-9964aaa343bd/download)
