### ISSUE TITLE
Physics for information science Unit 5 CS

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#345]

**Comment by kumarAman-123** [comment]
Hello @Eshu-99 , Please type the following document.
https://docs.google.com/document/d/16BPfhgINsYSYgNBCw_A97ipSLbVFl4VPDaDN-3JHlFI/edit#heading=h.dcnfm4myghfv

**Comment by Eshu-99** [comment]
@kumarAman-123 

PFA, HTML Files completed

[https://app.zenhub.com/files/350607556/49a15914-56ff-49df-8ff6-c42dbad3b948/download](https://app.zenhub.com/files/350607556/49a15914-56ff-49df-8ff6-c42dbad3b948/download)

**Comment by kumarAman-123** [comment]
Hello @RAJASEKHAR36 
Please upload the following Concept summary sheet.[https://app.zenhub.com/files/350607556/f4f42f34-e3f2-4ff2-92c7-761bfe3431e1/download](https://app.zenhub.com/files/350607556/f4f42f34-e3f2-4ff2-92c7-761bfe3431e1/download)

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 
The decks are moved to the staging.
Please go on with the QC with RMKCS1.

**Comment by kumarAman-123** [comment]
@RAJASEKHAR36 @meenakshy7..QC at the staging is done.

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 @meenakshy7 
It is moved to prod.
Please check it once
