### ISSUE TITLE
Physics for Electronics Engineering Unit 4 CS

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#346]

**Comment by kumarAman-123** [comment]
Hello @Eshu-99 , Please type the following document.
https://docs.google.com/document/d/1QXWBTsvljV4BUjcJKAEZdAJB5MuJzkWjXnTR0oV9lsY/edit

**Comment by Eshu-99** [comment]
@kumarAman-123 


PFA, HTML Files completed

[https://app.zenhub.com/files/350607556/7c7ff827-7f87-4e33-a729-da4aee506c79/download](https://app.zenhub.com/files/350607556/7c7ff827-7f87-4e33-a729-da4aee506c79/download)

**Comment by kumarAman-123** [comment]
@RAJASEKHAR36 ..Please upload the following concept summary sheet.
[https://app.zenhub.com/files/350607556/c0d79857-3f0d-4808-aabb-fb2930e32af0/download](https://app.zenhub.com/files/350607556/c0d79857-3f0d-4808-aabb-fb2930e32af0/download)

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 
The above attached sheet is uploaded to the staging.
Please go on with the QC with RMKCS1.

**Comment by kumarAman-123** [comment]
@meenakshy7 @RAJASEKHAR36 . QC at the staging is done

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 @meenakshy7 
It is moved to prod.
Please check it once
