### ISSUE TITLE
Physics for electronics Engineering Unit 5 CS

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#347]

**Comment by kumarAman-123** [comment]
@Eshu-99 , Please type this document.
https://docs.google.com/document/d/1aXRalIKFgiu020seyZfDb305BjhPQSwdvSxsUIFiuPY/edit#

**Comment by Eshu-99** [comment]
Hi Aman,

PFA, HTML Files completed

[https://app.zenhub.com/files/350607556/7d6b99e4-f3ce-46b1-9ff3-17a15b621064/download](https://app.zenhub.com/files/350607556/7d6b99e4-f3ce-46b1-9ff3-17a15b621064/download)

**Comment by kumarAman-123** [comment]
hello @RAJASEKHAR36 !
Please upload the following CS sheet.
[https://app.zenhub.com/files/350607556/eb17ad2a-695b-402f-8ddc-fd42ea26cca4/download](https://app.zenhub.com/files/350607556/eb17ad2a-695b-402f-8ddc-fd42ea26cca4/download)

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 
The above decks are uploaded.
Please go on with QC.

**Comment by kumarAman-123** [comment]
@RAJASEKHAR36 @meenakshy7 ..QC at the staging is done.

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 @meenakshy7 
It is moved to prod.
Please check it once
