### ISSUE TITLE
Physics for Civil Engineering Unit 5 CS

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#356]

**Comment by kumarAman-123** [comment]
Hello @Eshu-99  !! Pls type the following document.
https://docs.google.com/document/d/1XrTCHLOpdmX25htaDx9MWIKEVJTP2igqpyBUcTgFvvk/edit#

**Comment by Eshu-99** [comment]
Hi Aman

PFA, HTML Files completed

[https://app.zenhub.com/files/350607556/5812c29b-1a8a-44ae-b394-71952f6cf679/download](https://app.zenhub.com/files/350607556/5812c29b-1a8a-44ae-b394-71952f6cf679/download)

**Comment by kumarAman-123** [comment]
@RAJASEKHAR36 , Pls upload this document.
[Uploading... Concept summary sheet- RMKEC-Unit 5-Civil- Sem 2.xlsx]

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 @meenakshy7 
The above attached cs sheet is moved to the staging.
Please go on with the QC with the credentials of RMKEC1.

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 @meenakshy7 
The above attached decks are moved to the production.
Please check it once.
