### ISSUE TITLE
Physics for Mechanical Engineering Unit 4 CS

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#362]

**Comment by kumarAman-123** [comment]
Hello @Eshu-99 
Please type the following document
https://docs.google.com/document/d/1HM1JrC82-6Z1P2OqgHsjlqtHjLFFWKY9-5ALMZyf-2M/edit#heading=h.t68gg5wt658

**Comment by Eshu-99** [comment]
@kumarAman-123 

  PFA, HTML Files completed


[https://app.zenhub.com/files/350607556/47c35883-6a10-43d4-8a51-ca71dfb699b6/download](https://app.zenhub.com/files/350607556/47c35883-6a10-43d4-8a51-ca71dfb699b6/download)

**Comment by kumarAman-123** [comment]
@RAJASEKHAR36 , Please upload the CS Sheet and Deck Mapping.
[https://app.zenhub.com/files/350607556/ba22c3c9-491b-4458-974f-6760ae86ce18/download](https://app.zenhub.com/files/350607556/ba22c3c9-491b-4458-974f-6760ae86ce18/download)

@RAJASEKHAR36 ..Please see the Deck Mapping
[https://app.zenhub.com/files/350607556/4a63b53d-7e68-4377-9ddd-26598e14b927/download](https://app.zenhub.com/files/350607556/4a63b53d-7e68-4377-9ddd-26598e14b927/download)

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 @meenakshy7 
The above cs sheet is uploaded.
Please go on with the QC.

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 @meenakshy7 
The above attached decks are moved to the production.
Please check it once.
