### ISSUE TITLE
Physics for Mechanical Engineering Unit 5 CS

### ISSUE THREAD

**Issue by kumarAman-123** [edwisely-ai/Content#363]

**Comment by kumarAman-123** [comment]
Hello @Eshu-99 , pls type this document.
https://docs.google.com/document/d/1k8HF9tj-w1hL5sTRnumqbl3SBYkXbrVVGOaXKDJSHBg/edit#heading=h.j6qrxo4cf1n

**Comment by Eshu-99** [comment]
@kumarAman-123 

PFA, HTML Files completed.

[https://app.zenhub.com/files/350607556/3a8ce3cd-1529-4f74-ac5a-c0b2b7a7ff11/download](https://app.zenhub.com/files/350607556/3a8ce3cd-1529-4f74-ac5a-c0b2b7a7ff11/download)

**Comment by kumarAman-123** [comment]
Hello @RAJASEKHAR36 , Please upload the following CS sheet. The whole decks are arranged accordingly.
[https://app.zenhub.com/files/350607556/566b9ccd-209e-43cd-a7cf-b8894c635c9f/download](https://app.zenhub.com/files/350607556/566b9ccd-209e-43cd-a7cf-b8894c635c9f/download)

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 @meenakshy7 
The above decks are uploaded to the staging.
Please go on with the QC with RMKEC1.

**Comment by RAJASEKHAR36** [comment]
@kumarAman-123 @meenakshy7 
The above attached decks are moved to the production.
Please check it once.
