### ISSUE TITLE
Building materials-Unit 3- CS

### ISSUE THREAD

**Issue by Spandana-23** [edwisely-ai/Content#366]

**Comment by Spandana-23** [comment]
@Eshu-99 
Please do latex conversion for the file  have sent you in the mail.

**Comment by Eshu-99** [comment]
@Spandana-23 


PFA, Latex and typing completed

[https://app.zenhub.com/files/350607556/97ec323d-75c9-467b-8c9d-7374fbe0ef4e/download](https://app.zenhub.com/files/350607556/97ec323d-75c9-467b-8c9d-7374fbe0ef4e/download)

**Comment by Spandana-23** [comment]
@RAJASEKHAR36 
Please upload the CS sheet of U-3 BM to staging.
CS sheet: [https://app.zenhub.com/files/350607556/fe165dfd-4488-4808-ad6b-6b9385762da1/download](https://app.zenhub.com/files/350607556/fe165dfd-4488-4808-ad6b-6b9385762da1/download)

**Comment by RAJASEKHAR36** [comment]
@Spandana-23 
The above documents are uploaded to staging.
Please go on with the QC.

**Comment by Spandana-23** [comment]
@RAJASEKHAR36 
Please upload the updated CS sheet into production.
**Issue**: Index code for first deck is used in Construction techniques subject so cards got jumbled due to discontinuity of CS code. 
Updated CS sheet:
[https://app.zenhub.com/files/350607556/f24af1f5-66c2-43a8-bd6c-5d8c14a5c77b/download](https://app.zenhub.com/files/350607556/f24af1f5-66c2-43a8-bd6c-5d8c14a5c77b/download)

**Comment by RAJASEKHAR36** [comment]
@Spandana-23 
The above documents are uploaded to Prod.
Please check it once.
