### ISSUE TITLE
Building Materials-Unit-3-CS

### ISSUE THREAD

**Issue by Spandana-23** [edwisely-ai/Content#66]

**Comment by RAJASEKHAR36** [comment]
@Spandana-23 
The above attached cs sheet and decks are uploaded to the staging.
Please go on with the QC with the credentials RMKEC1.

**Comment by Spandana-23** [comment]
@RAJASEKHAR36 
QC is done. I made few corrections in deck mapping. Please upload the updated deck mapping to production.
Deck mapping file:
[https://app.zenhub.com/files/350607556/919eeac5-bdad-40e7-8563-be81bf1afe53/download](https://app.zenhub.com/files/350607556/919eeac5-bdad-40e7-8563-be81bf1afe53/download)

**Comment by RAJASEKHAR36** [comment]
@Spandana-23 
It is moved to the production.
Please check it once.
